### ISSUE TITLE
question about datasets

### ISSUE THREAD

**Issue by jasonyin20** [ralphc1212/bayes-mil#1]
what a great work.Thank you for opensource ,but i have a question about your datasets. what about the function of the shape_dict()

**Comment by ralphc1212** [comment]
Thanks. Could you please elaborate your question?

**Comment by jasonyin20** [comment]
where the file(datasets/dataset_generic.py) in your project, I didn't find it,woudl you didn't upload?

**Comment by ralphc1212** [comment]
It's addressed. Please check the new commit. Thx.
