### ISSUE TITLE
Question for applying the method to tumor subtyping task

### ISSUE THREAD

**Issue by dazhangyu123** [ralphc1212/bayes-mil#2]
While attempting to utilize this code for a subtyping task involving 3-class classification, I encountered an issue indicating that the variables prior_mu and prior_logvar are only configured for 2-class classification tasks. Since the experimental results presented in the paper are primarily focused on CAMELYON datasets, I would like to inquire whether the authors have explored applying their method to subtyping tasks as well.

**Comment by ralphc1212** [comment]
Sorry for the late response. The sub typing classification has been updated.
