### ISSUE TITLE
Calculating patch-level metrics such as FROC

### ISSUE THREAD

**Issue by DeVriesMatt** [ralphc1212/bayes-mil#4]
Hi,

Great repo and paper - I really enjoyed reading it!

You have calculated some patch-level localisation metrics in the paper, and I would like to do the same on an algorithm I am working on. Can you provide insight into how you calculated those? Specifically, the patch-level FROC and precision.

Thank you!

**Comment by ralphc1212** [comment]
Hi,

Thanks for paying attention to our work.

Simply speaking, we treat the patch-level localization problem as a binary classification problem and compare the prediction labels with the patch-level groundtruths. In our paper, the groundtruths are provided by the patch-level labels in CAMELYON16 and CAMELYON17. The results are averaged over all patches in a slide and all slides in a dataset.

Notably, the calculation of patch level FROC follows <Localization Results, Section 4.1 Results on Camelyon16> in [DSMIL](https://arxiv.org/pdf/2011.08939.pdf). Specifically, "The reported FROC score is defined as the average sensitivity at 6 predefined false positive rates: 1/4, 1/2, 1, 2, 4, and 8 FPs per WSI."

Precision is computed by definition 
average_over_all_slides(true_positive_patches_in_a_slide / ( true_positive_patches_in_a_slide + false_positive_patches_in_a_slide)).

Hope the information can help you. We will update the code for these metrics our repo later. Thanks!

**Comment by ralphc1212** [comment]
Hi, please refer to eval_froc.py for the patch-level evaluation metrics.
